<a href="https://colab.research.google.com/github/shreya-tss/PESU-IO/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/sample_data/california_housing_train.csv')
dataset.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]

In [ ]:
print(y)

[ 66900.  80100.  85700. ... 103600.  85800.  94600.]

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

  (0, 4529)	1.0
  (0, 5533)	-114.31
  (0, 5534)	34.19
  (0, 5535)	15.0
  (0, 5536)	1283.0
  (0, 5537)	1015.0
  (0, 5538)	472.0
  (0, 5539)	1.4936
  (1, 5045)	1.0
  (1, 5533)	-114.47
  (1, 5534)	34.4
  (1, 5535)	19.0
  (1, 5536)	1901.0
  (1, 5537)	1129.0
  (1, 5538)	463.0
  (1, 5539)	1.82
  (2, 526)	1.0
  (2, 5533)	-114.56
  (2, 5534)	33.69
  (2, 5535)	17.0
  (2, 5536)	174.0
  (2, 5537)	333.0
  (2, 5538)	117.0
  (2, 5539)	1.6509
  (3, 1285)	1.0
  :	:
  (16996, 5539)	2.5179
  (16997, 2458)	1.0
  (16997, 5533)	-124.3
  (16997, 5534)	41.84
  (16997, 5535)	17.0
  (16997, 5536)	531.0
  (16997, 5537)	1244.0
  (16997, 5538)	456.0
  (16997, 5539)	3.0313
  (16998, 2453)	1.0
  (16998, 5533)	-124.3
  (16998, 5534)	41.8
  (16998, 5535)	19.0
  (16998, 5536)	552.0
  (16998, 5537)	1298.0
  (16998, 5538)	478.0
  (16998, 5539)	1.9797
  (16999, 1603)	1.0
  (16999, 5533)	-124.35
  (16999, 5534)	40.54
  (16999, 5535)	52.0
  (16999, 5536)	300.0
  (16999, 5537)	806.0
  (16999, 5538)	270.0
  (16999, 5539)	3.0147

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

train_data = pd.read_csv("/content/sample_data/california_housing_train.csv")
test_data = pd.read_csv("/content/sample_data/california_housing_test.csv")


X_train = train_data[['median_income']]
y_train = train_data['median_house_value']

X_test = test_data[['median_income']]
y_test = test_data['median_house_value']


model = LinearRegression()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1))

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

[[321894.98 344700.  ]
 [195333.24 176500.  ]
 [287616.71 270500.  ]
 ...
 [140263.43  62000.  ]
 [181531.1  162500.  ]
 [403997.15 500001.  ]]
Mean Squared Error: 7009935982.6736